### ISSUE TITLE
Not sure how this all is supposed to work.. Seams abandoned

### ISSUE THREAD

**Issue by neilyoung** [MichielvdVelde/signal-fire#6]

**Comment by MichielvdVelde** [comment]
You're correct - I have not updated this package in a long time. I DO NOT RECOMMEND using it as-is!
I have no immediate plans to continue development, although I may eventually develop a successor.

**Comment by MichielvdVelde** [comment]
I've officially deprecated signal-fire. I will be working on a new version based on my WebSocket framework [luce](https://github.com/lucets/luce).

**Comment by neilyoung** [comment]
Don't worry :) Meanwhile I have written my own.
